Fraud/Entities/Fire/FireP01TroubledCodePosti.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DocumentFormat.OpenXml.CustomXmlSchemaReferences;
using DocumentFormat.OpenXml.Spreadsheet;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities
{
    [Table("FireP01_TroubledCodePosti", Schema = "fr")]
    public partial class FireP01TroubledCodePosti
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int ElhNo { get; set; }
        public int Bno { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime? BnSodurDateMiladi { get; set; }
        public int AgentId { get; set; }
        public string AgentName { get; set; }
        public int SodurId { get; set; }
        public string SodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string PostalCode { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

Fraud/Entities/Fire/FireP03BnNoLastPolicyId.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities
{
    [Table("FireP03_BnNoLastPolicyId", Schema = "fr")]
    public partial class FireP03BnNoLastPolicyId
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int ElhNo { get; set; }
        public int Bno { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime? BnSodurDateMiladi { get; set; }
        public int? AgentId { get; set; }
        public string AgentName { get; set; }
        public int SodurId { get; set; }
        public string SodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

Fraud/Entities/Fire/FireP04TafkikList.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities
{
    [Table("FireP04_TafkikList", Schema = "fr")]
    public partial class FireP04TafkikList
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int? Bno { get; set; }
        public int ElhNo { get; set; }
        public int? Mid { get; set; }
        public int? Eid { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime? BnSodurDateMiladi { get; set; }
        public int KhatarEzafiId { get; set; }
        public int EzafiRiskKind { get; set; }
        public string KhatarEzafiName { get; set; }
        public int MoreBimeId { get; set; }
        public string MoreBimeName { get; set; }
        public string MoreBimeSharh { get; set; }
        public decimal Sarmaye { get; set; }
        public int? Kind { get; set; }
        public string MoredKind { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Nationalcode { get; set; }
        public int AgentId { get; set; }
        public string AgentName { get; set; }
        public int SodurId { get; set; }
        public string SodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

Fraud/Entities/Fire/FireP06AfzayeshSarmaye.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities
{
    [Table("FireP06_AfzayeshSarmaye", Schema = "fr")]
    public partial class FireP06AfzayeshSarmaye
    {
        public int Id { get; set; }
        public int PolicyVerId { get; set; }
        public int PolicyId { get; set; }
        public int Bno { get; set; }
        public int Ro { get; set; }
        public int ElhNo { get; set; }
        public int PolicyTypeId { get; set; }
        public decimal Sarmaye { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime BnSodurDateMiladi { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Nationalcode { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int SodurId { get; set; }
        public string SodurName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int? DiffRate { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

Fraud/Entities/Fire/FireP07AnbarBazdid.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities
{
    [Table("FireP07_AnbarBazdid", Schema = "fr")]
    public partial class FireP07AnbarBazdid
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int? Bno { get; set; }
        public int? ElhNo { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime? BnSodurDateMiladi { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Nationalcode { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int BnSodurId { get; set; }
        public string BnSodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

Fraud/Controllers/FireController.cs
using Fraud.Convertor;
using Fraud.Infrastructure.Cache;
using Fraud.Models;
using Fraud.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Fraud.Models.Car;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace Fraud.Controllers
{
    [Route("/[controller]/[action]")]
    //[ApiController]
    //[Authorize]

    public class FireController : Controller
    {

        private readonly IFireServices _sv;
        readonly ICacheProvider _cache;
        private readonly ILogger<AccountController> _logger;
        public FireController(IFireServices sv, ICacheProvider cache , ILogger<AccountController> logger)
        {
            _cache = cache;
            _sv = sv;
            _logger = logger;
        }


        public IActionResult Index()
        {
            _logger.LogWarning("open Fire Indecator 1");
            return View();
        }

        NameValueCollection ToNameValueCollection<TKey, TValue>(IDictionary<TKey, TValue> dict)
        {
            var nameValueCollection = new NameValueCollection();
            foreach (var kvp in dict)
            {
                string value = null;
                if (kvp.Value != null)
                    value = kvp.Value.ToString();
                nameValueCollection.Add(kvp.Key.ToString(), value);
            }
            return nameValueCollection;
        }



        [HttpGet]
        public IActionResult FireP01TroubledCodePostiGet()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FireP01TroubledCodePostiPost()
        {
            try
            {
                var dict = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
                var parser = new Parser<FireP01TroubledCodePostiViewModel>(ToNameValueCollection<string, string>(dict),
                           _sv.GetFireP01TroubledCodePosti());
                var data = parser.Parse();
                var ss = Json(data);
                return Json(data);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpGet]
        [Route("{Id}")]
        public IActionResult FireP01TroubledCodePostiAddcmtGet(int id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _sv.OpenRecordFireP01TroubledCodePosti(id);
            if (obj == null)
            {
                return NotFound();
            }
            TempData["Id"] = id;
            return View("FireP01TroubledCodePostiAddcmtGet", obj);
        }

        [HttpPost]
        public IActionResult FireP01TroubledCodePostiAddcmtPost([FromBody] FireP01TroubledCodePostiViewModel fire)
        {
            var result = new { message = "", success = false };
            if (ModelState.IsValid)
            {
                var res = _sv.UpdateFireP01TroubledCodePosti(fire.Comment, fire.Id, fire.Status);
                if (res == null)
                {
                    result = new { message = "پیدا نشد", success = false };
                }
                else
                {
                    result = new { message = "عملیات با موفقیت انجام شد", success = true };
                }
                //return RedirectToAction("AddcommentToRecord1");
            }
            else
            {
                result = new { message = "معتبر نیست", success = false };

            }
            return Json(result);
        }

        [HttpPost]
        public IActionResult FireP01TroubledCodePostiToExcel()
        {

            var dict = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            dict["start"] = "0";
            dict["length"] = int.MaxValue.ToString();
            _cache.Set(string.Join("-", User.Identity.Name, nameof(FireP01TroubledCodePostiGet)), dict);
            return Ok();
        }
        [HttpPost]
        public IActionResult ExportFireP01TroubledCodePostiToExcel()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[12] {
                                                    new DataColumn("کد رایانه نامه "),
                                                    new DataColumn("شماره الحاقیه"),
                                                    new DataColumn("شماره بیمه نامه"),
                                                    new DataColumn("تاریخ صدور بیمه نامه"),
                                                    new DataColumn("واحد معرف"),
                                                    new DataColumn("واحد صدور"),
                                                    new DataColumn("شعبه واحد صدور"),
                                                    new DataColumn("بیمه گذار"),
                                                    new DataColumn("نام کاربر"),
                                                    new DataColumn("کد پستی"),
                                                    new DataColumn("وضعیت بررسی شاخص"),
                                                    new DataColumn("نظرات")
                                                   });
            var dict = (Dictionary<string, string>)_cache.Get(string.Join("-", User.Identity.Name, nameof(FireP01TroubledCodePostiGet)));
            var parser = new Parser<FireP01TroubledCodePostiViewModel>(ToNameValueCollection<string, string>(dict),
                         _sv.GetFireP01TroubledCodePosti());
            var data = parser.Parse();
            var lst = from ply in data.data
                      select ply;
            foreach (var item in lst)
            {
                dt.Rows.Add(item.PolicyId, item.ElhNo, item.Bno, item.BnSodurDate, item.AgentName,
                             item.SodurName, item.BranchName, item.CustomerName, item.UserName, item.PostalCode,
                             item.StatusName, item.Comment
                             );
            }
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream st = new MemoryStream())
                {
                    wb.SaveAs(st);
                    return File(st.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheatml.sheet", "Grid.xlsx");
                }
            }
        }


        ////
        ///

        [HttpGet]
        public IActionResult FireP03BnNoLastPolicyIdGet()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FireP03BnNoLastPolicyIdPost()
        {
            try
            {
                var dict = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
                var parser = new Parser<FireP03BnNoLastPolicyIdViewModel>(ToNameValueCollection<string, string>(dict),
                           _sv.GetFireP03BnNoLastPolicyId());
                var data = parser.Parse();
                var ss = Json(data);
                return Json(data);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpGet]
        [Route("{Id}")]
        public IActionResult FireP03BnNoLastPolicyIdAddcmtGet(int id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _sv.OpenRecordFireP03BnNoLastPolicyId(id);
            if (obj == null)
            {
                return NotFound();
            }
            TempData["Id"] = id;
            return View("FireP03BnNoLastPolicyIdAddcmtGet", obj);
        }

        [HttpPost]
        public IActionResult FireP03BnNoLastPolicyIdAddcmtPost([FromBody] FireP03BnNoLastPolicyIdViewModel fire)
        {
            var result = new { message = "", success = false };
            if (ModelState.IsValid)
            {
                var res = _sv.UpdateFireP03BnNoLastPolicyId(fire.Comment, fire.Id, fire.Status);
                if (res == null)
                {
                    result = new { message = "پیدا نشد", success = false };
                }
                else
                {
                    result = new { message = "عملیات با موفقیت انجام شد", success = true };
                }
                //return RedirectToAction("AddcommentToRecord1");
            }
            else
            {
                result = new { message = "معتبر نیست", success = false };

            }
            return Json(result);
        }

        [HttpPost]
        public IActionResult FireP03BnNoLastPolicyIdToExcel()
        {

            var dict = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            dict["start"] = "0";
            dict["length"] = int.MaxValue.ToString();
            _cache.Set(string.Join("-", User.Identity.Name, nameof(FireP03BnNoLastPolicyIdGet)), dict);
            return Ok();
        }
        [HttpPost]
        public IActionResult ExportFireP03BnNoLastPolicyIdToExcel()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[11] {
                                                    new DataColumn("کد رایانه بیمه نامه "),
                                                    new DataColumn("شماره الحاقیه"),
                                                    new DataColumn("شماره بیمه نامه"),
                                                    new DataColumn("تاریخ صدور بیمه نامه"),
                                                    new DataColumn("واحد معرف"),
                                                    new DataColumn("واحد صدور"),
                                                    new DataColumn("شعبه واحد صدور"),

Fraud/Views/Fire/FireP03BnNoLastPolicyIdGet.cshtml
@{
    ViewBag.IndexText = "قانون شماره یک آتش سوزی";
}
@section Style{

    <link rel="stylesheet" type="text/css" href="/DataTables/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="/DataTables/DataTables-1.11.2/css/jquery.dataTables.yadcf.css" />
    <link rel="stylesheet" type="text/css" href="/DataTables/DataTableCustom.css" />
    <link href="/dist/css/persianDatepicker-default.css" rel="stylesheet" />
}


<div class="card text-center">

    <div class="card-header bg-secondary row">
        <span class="btn btn-primary" onclick="showModal()">
            نمایش قوانین
        </span>
        <div class="col-md-9">
            شاخص 3-صدور آتش سوزی: کنترل ثبت کد رایانه بیمه نامه قبلی در فناوران در خصوص صدور بیمه نامه های تمدیدی
        </div>
    </div>

    <div class="card-body">
        <div style="width:100%;height:800px;cursor:pointer">
            <table id="SP2" class="table  table-fixed table-striped table-hover  overflow-y:scroll;">
            </table>
        </div>
    </div>
    <div class="card-footer text-muted"></div>
</div>

<form method="post" asp-controller="Fire" asp-action="ExportFireP03BnNoLastPolicyIdToExcel" class="mr-3">
    <input type="submit" id="GetExcel" value="انتقال به اکسل" class="btn btn-primary row" />
</form>

<div class="modalcontent">
    <partial name="/Views/Rules/_Rules.cshtml" />
</div>


@section Scripts{

    <script src="/dist/js/persianDatepicker.js"></script>
    <script type="text/javascript" src="/DataTables/datatables.min.js"></script>
    <script type="text/javascript" src="/DataTables/DataTables-1.11.2/js/jquery.dataTables.yadcf.js"></script>
    <script type="text/javascript" src="/DataTables/dataTables.fixedColumns.min.js"></script>
    <script type="text/javascript" src="/DataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/DataTables/dataTables.fixedHeader.min.js"></script>


    <script>

        var tableData;
        var dataTable;
        $(document).ready(function () {
            loadDataTable();
        });

        function loadDataTable() {

            //import { ConstPartDataTable } from "../../wwwroot/DataTables/js/CommonDataTable.js";
            //const funcs = {
            //    ConstPartDataTable
            //};
            $(".yadcf-filter-range-date").persianDatepicker();
            dataTable = $('#SP2').DataTable({
                /* funcs,*/
                /**/
         @Html.Partial("../Rules/_DataTableConfigPartial")

        columnDefs: [{ orderable: false, targets: [11] }],
        "ajax": {
            "url": "FireP03BnNoLastPolicyIdPost",
            "type": "POST",
            "datatype": "json"
        },
        "columns": [
            { "data": "Status", "name": "Status", "visible": false },
            { "data": "StatusName", "title": "وضعیت پرونده", "name": "StatusName", "visible": true },
            { "data": "PolicyId", "searchable": true, "title": "کد رایانه بیمه نامه", "name": "PolicyId", "autoWidth": true },
            { "data": "Bno", "searchable": true, "title": "شماره بیمه نامه", "name": "Bno", "autoWidth": true },
            { "data": "ElhNo", "searchable": true, "title": "شماره الحاقیه", "name": "ElhNo", "autoWidth": true },
            { "data": "BnSodurDateMiladi", "searchable": true, "title": "تاریخ صدور بیمه نامه", "name": "BnSodurDateMiladi", "autoWidth": true, "render": getBnSodurDateMiladi },
            { "data": "CustomerName", "searchable": true, "title": "بیمه گذار", "name": "CustomerName", "autoWidth": true },
            { "data": "AgentName", "searchable": true, "title": "واحد معرف", "name": "AgentName", "autoWidth": true },
            { "data": "SodurName", "searchable": true, "title": "واحد صدور", "name": "SodurName", "autoWidth": true },
            { "data": "BranchName", "searchable": true, "title": "شعبه واحد صدور", "name": "BranchName", "autoWidth": true },
            { "data": "UserName", "searchable": true, "title": "کاربر ثبت بیمه نامه", "name": "UserName", "autoWidth": true },
            {
                "data": "Id",
                "render": function (data, type, full, meta) {
                    return `<div class="text-center"> <a class="btn btn-info" onclick="GetComment(` + data + `)"   >نظرات</a> </div> `;
                }
            }
        ]
        , "createdRow": function (row, data, dataIndex) {
            if (data.Status == 1) {
                $(row).css({ "background": "#e5da1a" });
            }

            if (data.Status == 2) {
                $(row).css({ "background": "#f67a09" });

            }
            if (data.Status == 3) {
                $(row).css({ "background": "#df2b20" });

            }
            if (data.Status == 4) {
                $(row).css({ "background": "#9ACD32" });
            }
        },
        "rowCallback": function (row, data) {
            $(row).dblclick(function () { GetComment(data.Id) });
        }
    });


    yadcf.init(dataTable, [
        {
            column_number: 1,
            filter_type: "text"
        }
        ,
        {
            column_number: 2,
            filter_type: "text"
        },
        {
            column_number: 3,
            filter_type: "text"
        },
        {
            column_number: 4,
            filter_type: "text"
        },
        {
            column_number: 5,
            filter_type: "range_date",
            filter_delay: 2000
        },
        {
            column_number: 6,
            filter_type: "text",
            filter_delay: 2000
        },
        {
            column_number: 7,
            filter_type: "text"
        },
        {
            column_number: 8,
            filter_type: "text"
        },
        {
            column_number: 9,
            filter_type: "text"
        },
        {
            column_number: 10,
            filter_type: "text"
        }
    ]);
}




function getBnSodurDateMiladi(data, type, full, meta) {
    return full.BnSodurDate;
}
function GetComment(id) {
    window.location.href = '/Fire/FireP03BnNoLastPolicyIdAddcmtGet/' + id;
}

//$(document).ajaxComplete(function (event, request, settings) {
//    console.log(settings)
//    if (settings.url.indexOf('SalesP1LessPishPardakhtPost') > -1)
//    datatableParam = settings.data;
//});


var datatableParam;
var counter = 0;
var counterB = 0;
$(document).ajaxSend(function (event, request, settings) {
    // console.log(settings)
    if (settings.url.indexOf('FireP03BnNoLastPolicyIdPost') > -1) {
        datatableParam = settings.data;
        console.log("datatableParamS", counterB++, datatableParam)
    }
});


$("#GetExcel").click(function () {
    setExcellData();
    $(this).closest('form').submit();
});
function setExcellData() {
    $.post({
        type: 'POST',
        url: '/Fire/FireP03BnNoLastPolicyIdToExcel',
        data: datatableParam,
        dataType: 'json',
        success: function (data) {
        }
    });
}


    </script>

}